---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-core
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
    spec:
      containers:
      - env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: iot-core
              resource: limits.memory
        - name: DEV_MGMT_URL
          value: "http://iot-device-mgmt"
        - name: MEASUREMENTS_URL
          value: "http://iot-events"
        - name: RABBITMQ_HOST
          value: rabbitmq
        image: ghcr.io/diwise/iot-core:changeme
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: default-port
        name: iot-core
        ports:
        - containerPort: 8080
          name: default-port
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 100Mi
        startupProbe:
          httpGet:
            path: /health
            port: default-port
        volumeMounts:
          - name: conf-volume
            mountPath: /opt/diwise/config
      serviceAccountName: iot-core
      volumes:
        - name: conf-volume
          configMap:
            name: core-cfg-cm
